Jest 27
pckhoi/jest-bench pull request #1
Opened 2021-10-30 00:57 UTC by NathanPB

I updated this to work with the current latest major version of jest =) Seems to be working fine

2021-10-31 00:52 UTC, pckhoi requested changes
Hello, thank you for the pull request. However, I see this error when I try to test. Are you seeing this?
```

 FAIL  test/setup_teardown.bench.ts
  ● Test suite failed to run

      ● Test suite failed to run

        TypeError: Cannot read property 'bind' of undefined

      at jestAdapter (node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:30:56)
```
It seems there is something breaking alright. Can you please take care of this?

2021-10-31 00:52 UTC, pckhoi commented on package.json
> -    "test:node": "npm run build && jest --projects jest-node.config.ts",
Please change this back, this is needed to test the reporter.

2021-10-31 00:52 UTC, pckhoi commented on test/error.bench.ts
> +    expect(() => { throw new Error("something wrong!") }).toThrow();
This need to throw so that I can see the test report the error.

2021-10-31 00:52 UTC, pckhoi commented on test/basic.bench.ts
> +import { benchmarkSuite } from "../src";
Please change this back. Import from dist more accurately present usage of this library.

2021-10-31 00:52 UTC, pckhoi commented on test/setup_teardown.bench.ts
> +import { benchmarkSuite } from "../src";
This.

2021-11-01 22:33 UTC, NathanPB commented
Ima check that all in a few days, for my experience it looks like jest-circus is kinda broken, couldn't find a solution yet

2021-11-02 15:18 UTC, NathanPB commented
The requested changes are done, just had to revert one commit. Jest-circus still broken tho

2021-11-04 13:11 UTC, pckhoi commented
Looks like the issue is that jest-electron still stucks at jest@v24: https://github.com/hustcc/jest-electron/issues/32

Let's see how that goes.

2021-11-04 18:19 UTC, NathanPB commented
Ye, but this issue is more than a year old, I don't think it's gonna happen anytime soon... I think we will be stuck with jest 24 forever

For the time being I published my fork on npmjs because I needed this library for my personal use. It's on ``@nathanpb/jest-bench`` (if anyone reading this in the future need it)

2021-11-14 02:44 UTC, pckhoi commented
I have publish `jest-bench@27.3.1` for those who want to use jest version 27. From now on jest-bench will take its version after jest's. Anyone who is still stuck at jest@26 can install `jest-bench@26.6.3`.

2021-11-14 02:44 UTC, closed without merging